#! /bin/sh


CC="clang" CXX="clang++" LDFLAGS="-fuse-ld=mold" \
  cmake ../llvm -GNinja \
  -DCMAKE_BUILD_TYPE=Release \
  -DLLVM_TARGETS_TO_BUILD=Native \
  -DLLVM_INCLUDE_TESTS=OFF \
  -DLLVM_INCLUDE_UTILS=OFF \
  -DLLVM_BUILD_TOOLS=OFF \
  -DLLVM_BUILD_UTILS=OFF \
  -DLLVM_CCACHE_BUILD=ON \
  -DLLVM_ENABLE_PROJECTS="clang" \
  -DLLVM_DEFAULT_TARGET_TRIPLE="$(rpm --eval '%{_host}')" \
  -DLLVM_BUILD_LLVM_DYLIB=ON \
  -DLLVM_LINK_LLVM_DYLIB=ON \
  -DLLVM_INCLUDE_BENCHMARKS=OFF \
  -DCLANG_INCLUDE_TESTS=OFF \
  -DCLANG_BUILD_CLANG_DYLIB=ON \
  -DCLANG_LINK_CLANG_DYLIB=ON \
  -DCLANG_BUILD_TOOLS=ON


